/*
 * Generated VerificationEvidenceStateIndex schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/verification-evidence/src/schemas.ts
 * Source path: tools/verification-evidence/src/schemas.ts
 * Rebuild: bun run sync:verification-evidence-cli
 */
export interface VerificationEvidenceStateIndex {
  definitionVersion: 2;
  entries: {
    id: string;
    keys: {
      /**
       * @minItems 1
       */
      search: [unknown, ...unknown[]];
      /**
       * @minItems 1
       */
      verification: [unknown, ...unknown[]];
    };
    state: {
      endLine: number;
      /**
       * @minItems 1
       */
      entries: [string, ...string[]];
      id: string;
      line: number;
      summary: string;
      title: string;
      verification: "test" | "check";
      searchText: string;
    };
  }[];
  /**
   * @minItems 2
   */
  keyDefinitions: [unknown, unknown, ...unknown[]];
  metadata: Record<string, never>;
  namespace: "verification-evidence";
  schemaVersion: 2;
  sourceRevision: string;
}
