/*
 * Generated VerificationEvidenceConfig schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/verification-evidence/src/schemas.ts
 * Source path: tools/verification-evidence/src/schemas.ts
 * Rebuild: bun run sync:verification-evidence-cli
 */
export interface VerificationEvidenceConfig {
  caseIdPattern?: string;
  catalogPath?: string;
  indexPath?: string;
  schemaVersion: 1;
}
