/*
 * Generated RegexCollectorConfig schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/src/schemas.ts
 * Source path: tools/test-evidence/src/schemas.ts
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface RegexCollectorConfig {
  builtinDetectors?: (
    "rust" | "typescript" | "javascript" | "python" | "go" | "java" | "csharp"
  )[];
  excludeGlobs?: string[];
  includeGlobs?: string[];
  patterns?: {
    excludeGlobs?: string[];
    flags?: string;
    id: string;
    /**
     * @minItems 1
     */
    includeGlobs: [string, ...string[]];
    language: string;
    offsetGroup?: number;
    pattern: string;
  }[];
  schemaVersion: 1;
}
