/*
 * Generated TestEvidenceStateIndex schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/src/schemas.ts
 * Source path: tools/test-evidence/src/schemas.ts
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface TestEvidenceStateIndex {
  definitionVersion: 2;
  entries: {
    id: string;
    keys: {
      /**
       * @minItems 1
       */
      "review-triggered"?: [unknown, ...unknown[]];
      /**
       * @minItems 1
       */
      search: [unknown, ...unknown[]];
      /**
       * @minItems 1
       */
      status: [unknown, ...unknown[]];
      /**
       * @minItems 1
       */
      verification: [unknown, ...unknown[]];
    };
    state: {
      codePath: string | null;
      endLine: number;
      id: string;
      lastReview: {
        at: string;
        commit: string;
        result: "pass" | "findings" | "blocked";
      } | null;
      line: number;
      scope: string[];
      status: "active" | "planned";
      summary: string;
      title: string;
      verification: "automated" | "review" | "exempt";
      trigger: null;
    };
  }[];
  /**
   * @minItems 4
   */
  keyDefinitions: [unknown, unknown, unknown, unknown, ...unknown[]];
  namespace: "test-evidence";
  schemaVersion: 1;
  sourceRevision: string;
}
