/*
 * Generated TestEntryInventory schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/src/schemas.ts
 * Source path: tools/test-evidence/src/schemas.ts
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface TestEntryInventory {
  diagnostics: {
    blocking: boolean;
    caseId?: string;
    category:
      "catalog" | "config" | "discovery" | "git" | "inventory" | "mapping" | "review";
    code: string;
    column?: number;
    detectorId?: string;
    line?: number;
    message: string;
    path?: string;
    severity: "error" | "warning";
  }[];
  entries: {
    column: number;
    /**
     * @minItems 1
     */
    detectorIds: [string, ...string[]];
    id: string;
    language: string;
    line: number;
    offset: number;
    path: string;
  }[];
  markers: {
    caseId: string;
    line: number;
    offset: number;
    path: string;
    role: "main" | "derived" | "exempt";
    targetEntryId: string | null;
  }[];
  schemaVersion: 1;
}
