/*
 * Generated TestEvidenceLedgerConfig schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/src/schemas.ts
 * Source path: tools/test-evidence/src/schemas.ts
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface TestEvidenceLedgerConfig {
  caseIdPattern?: string;
  catalogPath?: string;
  reviewMaxAgeDays?: number;
  reviewTriggers?: "warn" | "error";
  schemaVersion: 3;
  unregisteredTestEntries?: "ignore" | "warn" | "error";
}
