/*
 * Generated TestEvidenceStateIndex schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/src/core-schemas.ts
 * Source path: tools/test-evidence/src/core-schemas.ts
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface TestEvidenceStateIndex {
  definitionVersion: 6;
  entries: {
    [k: string]: {
      title: string;
      sourcePath: string;
      tags: string[];
      /**
       * @minItems 1
       */
      testIds: [string, ...string[]];
    };
  };
  metadata: {};
  namespace: "test-evidence";
  schemaVersion: 4;
  sourceRevision: {
    entries: {
      [k: string]: string;
    };
    metadata: string;
  };
}
