/*
 * Generated TestEvidenceEntitySnapshot schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/src/core-schemas.ts
 * Source path: tools/test-evidence/src/core-schemas.ts
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface TestEvidenceEntitySnapshot {
  schemaVersion: 2;
  source: {
    projectId: string;
    scopeId: string;
    revision: string;
  };
  completeness: "complete" | "partial";
  entities: {
    id: string;
    name: string;
    /**
     * @minItems 1
     */
    locators: [string, ...string[]];
  }[];
}
