/*
 * Generated TestEvidenceReport schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/src/schemas.ts
 * Source path: tools/test-evidence/src/schemas.ts
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface TestEvidenceReport {
  diagnostics: {
    blocking: boolean;
    caseId?: string;
    category: "catalog" | "config" | "index";
    code: string;
    column?: number;
    line?: number;
    message: string;
    path?: string;
    severity: "error" | "warning";
  }[];
  schemaVersion: 2;
  summary: {
    testCases: number;
  };
}
