await import("./evolution/evolution-01.test.ts");
await import("./evolution/evolution-02.test.ts");
await import("./evolution/evolution-03.test.ts");
await import("./evolution/evolution-04.test.ts");
await import("./evolution/evolution-05.test.ts");
await import("./evolution/evolution-06.test.ts");
await import("./evolution/evolution-07.test.ts");
await import("./evolution/evolution-08.test.ts");
await import("./successor-relation-overrides.test.ts");
