await import("./schema-index.test.ts");
await import("./graph-projection.test.ts");
await import("./task-list-renderer.test.ts");
await import("./lifecycle.test.ts");
await import("./runtime.test.ts");
await import("./store.test.ts");
await import("./cli.test.ts");
await import("./task-removal.test.ts");
await import("./generated-artifacts.test.ts");
