/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/cli-contract.ts
 * Source path: tools/task-graph/src/cli-contract.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import type { TaskGraphResult, TaskIndexStageResult, TaskListItem } from "./types.mjs";
export type CliIo = {
    stdout: (text: string) => void;
};
export type GlobalArguments = {
    help: boolean;
    indexPath?: string;
    json: boolean;
    remaining: string[];
    root: string;
    version: boolean;
};
export type CliInvocation = {
    kind: "help";
    pathTokens: readonly string[];
} | {
    kind: "index-stage";
    tokens: readonly string[];
} | {
    kind: "json-command";
    tokens: readonly string[];
} | {
    columns: number;
    kind: "task-list";
    tokens: readonly string[];
} | {
    kind: "version";
};
type TaskListResult = TaskGraphResult<Record<string, TaskListItem>>;
type TaskIndexStageCliResult = TaskGraphResult<TaskIndexStageResult>;
export type CliOutput = {
    kind: "json";
    result: TaskGraphResult;
} | {
    kind: "index-stage";
    result: TaskIndexStageCliResult;
} | {
    columns: number;
    kind: "task-list";
    result: TaskListResult;
};
export type OptionDefinition = {
    kind: "boolean" | "string";
    multiple?: boolean;
};
export type ParsedCommandOptions = {
    positionals: string[];
    values: Record<string, string | string[] | true>;
};
export type DispatchResult = {
    revision: number;
    data: unknown;
} | {
    revision: number | null;
    data: unknown;
};
export type CommandHelp = {
    input?: {
        default: "stdin";
        fileOption: "--file";
        format: "json";
    };
    options: readonly HelpParameter[];
    positionals: readonly HelpParameter[];
    requiresMutationRuntime?: true;
    usage: string;
};
export type HelpParameter = {
    default?: boolean | string | number | null;
    enum?: readonly string[];
    multiple?: boolean;
    name: string;
    required: boolean;
    type: "boolean" | "integer" | "key-value" | "string";
};
export type TaskGraphCliOptions = {
    io?: CliIo;
    serviceOptions?: Omit<import("./service.mjs").TaskGraphServiceOptions, "root" | "indexPath">;
};
export {};
