/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/cli.ts
 * Source path: tools/task-graph/src/cli.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import { type TaskGraphServiceOptions } from "./service.mjs";
type CliIo = {
    stdout: (text: string) => void;
};
export type TaskGraphCliOptions = {
    io?: CliIo;
    serviceOptions?: Omit<TaskGraphServiceOptions, "root" | "indexPath">;
};
export declare function runTaskGraphCli(argv?: readonly string[], options?: TaskGraphCliOptions): Promise<number>;
export * from "./index.mjs";
