/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/engine-content.ts
 * Source path: tools/task-graph/src/engine-content.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import type { TaskControlInput, TaskGraphRevisionOperation, TaskIndex } from "./types.mjs";
export declare const compareText: (left: string, right: string) => number;
export type IndexMutation<TData> = {
    index: TaskIndex;
    data: TData;
};
export declare function formatTaskId(value: number): string;
export declare function nextRevision(index: TaskIndex): number;
export declare function cloneIndex(index: TaskIndex): TaskIndex;
export declare function requireExpectedRevision(index: TaskIndex, expectedRevision: number): void;
export declare function requireTask(index: TaskIndex, taskId: string): import("./types.mjs").TaskEntry;
export declare function canonicalNow(now: Date): string;
export declare function boundedString(value: unknown, label: string, maximum: number, options?: {
    singleLine?: boolean;
}): string;
export declare function updateTaskTime(index: TaskIndex, taskId: string, now: string): void;
export declare function parseControl(input: TaskControlInput): import("./types.mjs").TaskControl;
export declare function createTask(index: TaskIndex, operation: Extract<TaskGraphRevisionOperation, {
    kind: "create-task";
}>, now: string): string;
export declare function updateTaskContent(index: TaskIndex, operation: Extract<TaskGraphRevisionOperation, {
    kind: "update-task-content";
}>, now: string): void;
export declare function updateTaskControl(index: TaskIndex, operation: Extract<TaskGraphRevisionOperation, {
    kind: "update-task-control";
}>, now: string): void;
export declare function setParent(index: TaskIndex, operation: Extract<TaskGraphRevisionOperation, {
    kind: "set-parent";
}>, now: string): void;
export declare function setDependency(index: TaskIndex, operation: Extract<TaskGraphRevisionOperation, {
    kind: "set-dependency";
}>, now: string): void;
export declare function setExclusion(index: TaskIndex, operation: Extract<TaskGraphRevisionOperation, {
    kind: "set-exclusion";
}>, now: string): void;
export declare function resolveTaskReference(value: string, aliases: ReadonlyMap<string, string>): string;
export declare function resolveOperationAliases(operation: TaskGraphRevisionOperation, aliases: ReadonlyMap<string, string>): TaskGraphRevisionOperation;
