/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/engine-claim.ts
 * Source path: tools/task-graph/src/engine-claim.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import { projectTaskGraph } from "./graph.mjs";
import { TaskGraphError } from "./errors.mjs";
import type { IndexMutation } from "./engine-content.mjs";
import type { ClaimTaskOptions, TaskIndex } from "./types.mjs";
export declare function mutateExecution<TData>(current: TaskIndex, taskId: string, now: Date, mutate: (candidate: TaskIndex, timestamp: string) => TData): IndexMutation<TData>;
export declare function leaseDurationMilliseconds(durationSeconds: number): number;
export declare function canonicalLeaseId(value: string): string;
export declare function requireRunningLease(index: TaskIndex, taskId: string, leaseId: string, now: Date, allowExpired: boolean): {
    phase: "running";
    attempt: number;
    lease: import("./types.mjs").TaskLease;
};
export declare function claimTask(current: TaskIndex, options: ClaimTaskOptions & {
    leaseUuid: string;
}, now: Date): IndexMutation<{
    taskId: string;
    leaseId: string;
    expiresAt: string;
}>;
type ClaimMutationContext = Readonly<{
    actor: string;
    duration: number;
    now: Date;
    options: ClaimTaskOptions & {
        leaseUuid: string;
    };
    recovering: boolean;
}>;
export declare function applyClaimMutation(candidate: TaskIndex, timestamp: string, context: ClaimMutationContext): {
    taskId: string;
    leaseId: string;
    expiresAt: string;
};
export declare function validateClaimState(candidate: TaskIndex, task: TaskIndex["tasks"][string], projection: ReturnType<typeof projectTaskGraph>["tasks"][string] | undefined, context: ClaimMutationContext): void;
export declare function validateExpiredClaimRecovery(candidate: TaskIndex, execution: Extract<TaskIndex["tasks"][string]["state"]["execution"], {
    phase: "running";
}>, projection: ReturnType<typeof projectTaskGraph>["tasks"][string] | undefined, context: ClaimMutationContext): void;
export declare function claimStateConflict(taskId: string, projection: ReturnType<typeof projectTaskGraph>["tasks"][string] | undefined): TaskGraphError;
export declare function assertLeaseAvailable(candidate: TaskIndex, taskId: string, leaseId: string): void;
export {};
