/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/engine-removal.ts
 * Source path: tools/task-graph/src/engine-removal.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import type { IndexMutation } from "./engine-content.mjs";
import type { RemoveTasksOptions, TaskExecutionPhase, TaskIndex } from "./types.mjs";
type TaskRemovalBlocker = {
    kind: "task-not-terminal";
    taskId: string;
    phase: TaskExecutionPhase;
} | {
    kind: "parent-crosses-selection" | "child-crosses-selection" | "dependency-crosses-selection" | "exclusion-crosses-selection";
    taskId: string;
    relatedTaskId: string;
};
export declare function removeTasks(current: TaskIndex, options: RemoveTasksOptions): IndexMutation<{
    removedTaskIds: string[];
}>;
export declare function validateRemovalSelection(options: RemoveTasksOptions): void;
export declare function collectRemovalBlockers(current: TaskIndex, selected: ReadonlySet<string>): TaskRemovalBlocker[];
export declare function selectedTaskRemovalBlockers(current: TaskIndex, taskId: string, selected: ReadonlySet<string>): TaskRemovalBlocker[];
export declare function remainingTaskRemovalBlockers(taskId: string, task: TaskIndex["tasks"][string], selected: ReadonlySet<string>): TaskRemovalBlocker[];
type CrossingRelationRequest = Readonly<{
    blockers: TaskRemovalBlocker[];
    includeSelected: boolean;
    kind: "dependency-crosses-selection" | "exclusion-crosses-selection";
    relatedIds: readonly string[];
    selected: ReadonlySet<string>;
    taskId: string;
}>;
export declare function appendCrossingRelations(request: CrossingRelationRequest): void;
export declare function sortRemovalBlockers(blockers: TaskRemovalBlocker[]): void;
export declare function removeSelectedTasks(current: TaskIndex, selected: ReadonlySet<string>): IndexMutation<{
    removedTaskIds: string[];
}>;
export {};
