/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/engine.ts
 * Source path: tools/task-graph/src/engine.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
export type { IndexMutation } from "./engine-content.mjs";
export { applyTaskGraphOperations } from "./engine-apply.mjs";
export { claimTask } from "./engine-claim.mjs";
export { cancelTask, completeTask, failTask, releaseTask, renewTaskLease, retryTask } from "./engine-lifecycle.mjs";
export { removeTasks } from "./engine-removal.mjs";
