/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/errors.ts
 * Source path: tools/task-graph/src/errors.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import type { JsonObject, TaskGraphErrorCode } from "./types.mjs";
export declare class TaskGraphError extends Error {
    readonly code: TaskGraphErrorCode;
    readonly details: JsonObject;
    readonly retryable: boolean;
    constructor(code: TaskGraphErrorCode, message: string, details?: unknown, options?: ErrorOptions);
}
export declare function taskGraphError(error: unknown, fallbackCode?: TaskGraphErrorCode): TaskGraphError;
