/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/graph-projection.ts
 * Source path: tools/task-graph/src/graph-projection.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import type { TaskGraphProjection, TaskIndex, TaskProjection } from "./types.mjs";
export declare function projectOneTask(index: TaskIndex, taskId: string, now: Date, children: Map<string, string[]>, dependents: Map<string, string[]>): TaskProjection;
export declare function projectTaskGraph(index: TaskIndex, now: Date): TaskGraphProjection;
export declare function detectCycle(edges: Map<string, Set<string>>): string[] | null;
