/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/graph.ts
 * Source path: tools/task-graph/src/graph.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import type { ScopeProjection, TaskConstraintSource, TaskIndex, TaskProjection, TaskScope } from "./types.mjs";
export declare function childrenByTask(scope: TaskScope): Map<string, string[]>;
export declare function ancestorIds(scope: TaskScope, taskId: string): string[];
export declare function descendantIds(scope: TaskScope, taskId: string): string[];
export declare function effectiveControl(scope: TaskScope, taskId: string): TaskProjection["effectiveControl"];
export declare function effectiveDependencySources(scope: TaskScope, taskId: string): TaskConstraintSource[];
export declare function effectiveExclusionSources(scope: TaskScope, taskId: string): TaskConstraintSource[];
export declare function projectScope(index: TaskIndex, scopeId: string, now: Date): ScopeProjection;
export declare function validateTaskIndexGraph(index: TaskIndex): string[];
export declare function assertProtectedTopologyUnchanged(before: TaskScope, after: TaskScope): void;
export declare function assertRunningControlUnchanged(before: TaskScope, after: TaskScope): void;
