/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/graph-validation.ts
 * Source path: tools/task-graph/src/graph-validation.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import type { TaskIndex } from "./types.mjs";
export declare function validateTaskIndexGraph(index: TaskIndex): string[];
type TaskEntry = TaskIndex["tasks"][string];
type DirectValidationContext = Readonly<{
    index: TaskIndex;
    issues: string[];
    leaseOwners: Map<string, string>;
    parentEdges: Map<string, Set<string>>;
    task: TaskEntry;
    taskChildren: readonly string[];
    taskId: string;
    taskIds: ReadonlySet<string>;
}>;
export declare function validateDirectRelations(context: DirectValidationContext): void;
export declare function validateDirectExecution(context: DirectValidationContext): void;
export declare function validateLease(taskId: string, lease: Extract<TaskEntry["state"]["execution"], {
    phase: "running";
}>["lease"], leaseOwners: Map<string, string>, issues: string[]): void;
export declare function validateCancelledDescendants(index: TaskIndex, issues: string[]): void;
export declare function validateHierarchicalExclusions(index: TaskIndex, taskIds: readonly string[], issues: string[]): void;
export declare function validateEffectiveConstraints(index: TaskIndex, taskIds: readonly string[], children: ReadonlyMap<string, readonly string[]>, issues: string[]): Map<string, Set<string>>;
export declare function validateExecutionEvidence(index: TaskIndex, taskIds: readonly string[], children: ReadonlyMap<string, readonly string[]>, issues: string[]): void;
export declare function validateDependencyEvidence(index: TaskIndex, taskId: string, task: TaskEntry, issues: string[]): void;
export declare function validateRunningEvidence(index: TaskIndex, taskId: string, issues: string[]): void;
export declare function topologySignature(index: TaskIndex, taskId: string): string;
export declare function assertProtectedTopologyUnchanged(before: TaskIndex, after: TaskIndex): void;
export declare function assertRunningControlUnchanged(before: TaskIndex, after: TaskIndex): void;
export {};
