/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/index.ts
 * Source path: tools/task-graph/src/index.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import type { TaskGraphApplyRequest, TaskIndex } from "./types.mjs";
export { TaskGraphError } from "./errors.mjs";
export { applyTaskGraphOperations, cancelTask, claimTask, completeTask, failTask, releaseTask, removeTasks, renewTaskLease, retryTask, type IndexMutation } from "./engine.mjs";
export { projectTaskGraph, validateTaskIndexGraph } from "./graph.mjs";
export { TaskGraphService, type ServiceResult, type TaskGraphServiceOptions, type TaskSummary } from "./service.mjs";
export * from "./types.mjs";
export declare function emptyTaskIndex(): TaskIndex;
export declare function parseTaskGraphApplyRequest(input: unknown): TaskGraphApplyRequest;
export declare function parseTaskIndex(input: unknown): TaskIndex;
export declare function serializeTaskIndex(index: TaskIndex): string;
