/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/service.ts
 * Source path: tools/task-graph/src/service.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import type { CancelTaskOptions, ClaimTaskOptions, Clock, CompleteTaskOptions, ScopeCloseProjection, ScopeProjection, TaskControlInput, TaskGraphApplyRequest, TaskGraphApplyResult, TaskEffectiveState, TaskExecutionPhase, TaskIndex, TaskIndexInfo } from "./types.mjs";
export type TaskGraphServiceOptions = {
    clock?: Clock;
    indexPath?: string;
    root?: string;
};
export type ServiceResult<TData> = {
    revision: number;
    data: TData;
};
export type ScopeSummary = {
    scopeId: string;
    key: string;
    bindings: Record<string, string>;
    taskCount: number;
    topTaskCount: number;
    close: ScopeCloseProjection;
};
export type ListScopesOptions = {
    key?: string;
} & ({
    bindingKind: string;
    bindingValue: string;
} | {
    bindingKind?: never;
    bindingValue?: never;
});
export type TaskSummary = {
    taskId: string;
    title: string;
    parentId: string | null;
    phase: TaskExecutionPhase;
    effectiveState: TaskEffectiveState;
    nextAction: "claim" | "complete" | null;
};
export declare class TaskGraphService {
    private readonly clock;
    private readonly leaseIdGenerator;
    constructor(options?: TaskGraphServiceOptions);
    init(): Promise<ServiceResult<TaskIndexInfo>>;
    info(): Promise<ServiceResult<TaskIndexInfo>>;
    readIndex(): Promise<ServiceResult<TaskIndex>>;
    apply(request: TaskGraphApplyRequest): Promise<ServiceResult<TaskGraphApplyResult>>;
    listScopes(options?: ListScopesOptions): Promise<ServiceResult<Record<string, ScopeSummary>>>;
    showScope(scopeId: string): Promise<ServiceResult<{
        scope: TaskIndex["scopes"][string];
        projection: ScopeProjection;
    }>>;
    listTasks(scopeId: string): Promise<ServiceResult<Record<string, TaskSummary>>>;
    showTask(scopeId: string, taskId: string): Promise<ServiceResult<{
        task: TaskIndex["scopes"][string]["tasks"][string];
        projection: ScopeProjection["tasks"][string];
    }>>;
    actionable(scopeId: string): Promise<ServiceResult<{
        tasks: ScopeProjection["actionable"];
        order: string[];
    }>>;
    claim(options: ClaimTaskOptions): Promise<ServiceResult<{
        taskId: string;
        leaseId: string;
        expiresAt: string;
    }>>;
    renew(options: {
        scopeId: string;
        taskId: string;
        leaseId: string;
        durationSeconds?: number;
    }): Promise<ServiceResult<{
        taskId: string;
        leaseId: string;
        expiresAt: string;
    }>>;
    release(options: {
        scopeId: string;
        taskId: string;
        leaseId: string;
        control: TaskControlInput;
    }): Promise<ServiceResult<{
        taskId: string;
        phase: "idle";
    }>>;
    complete(options: CompleteTaskOptions): Promise<ServiceResult<{
        taskId: string;
        phase: "succeeded";
    }>>;
    fail(options: {
        scopeId: string;
        taskId: string;
        leaseId: string;
        reason: string;
    }): Promise<ServiceResult<{
        taskId: string;
        phase: "failed";
    }>>;
    retry(options: {
        scopeId: string;
        taskId: string;
        expectedRevision: number;
    }): Promise<ServiceResult<{
        taskId: string;
        phase: "idle";
    }>>;
    cancel(options: CancelTaskOptions): Promise<ServiceResult<{
        taskId: string;
        cancelledTaskIds: string[];
    }>>;
    closeScopes(options: {
        expectedRevision: number;
        scopeIds: string[];
        resultsDelivered: true;
    }): Promise<ServiceResult<{
        closedScopeIds: string[];
        scopes: Record<string, ScopeCloseProjection>;
    }>>;
    private executionMutation;
}
