/*
 * Generated task graph SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/task-graph/src/service.ts
 * Source path: tools/task-graph/src/service.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/task-graph
 * Rebuild: bun run sync:task-graph-cli
 */
import type { CancelTaskOptions, ClaimTaskOptions, Clock, CompleteTaskOptions, RemoveTasksOptions, TaskControlInput, TaskEffectiveState, TaskExecutionPhase, TaskGraphApplyRequest, TaskGraphApplyResult, TaskGraphProjection, TaskIndex, TaskIndexInfo } from "./types.mjs";
export type TaskGraphServiceOptions = {
    clock?: Clock;
    indexPath?: string;
    root?: string;
};
export type ServiceResult<TData> = {
    revision: number;
    data: TData;
};
export type TaskSummary = {
    taskId: string;
    title: string;
    parentId: string | null;
    phase: TaskExecutionPhase;
    effectiveState: TaskEffectiveState;
    nextAction: "claim" | "complete" | null;
};
export declare class TaskGraphService {
    private readonly clock;
    private readonly leaseIdGenerator;
    constructor(options?: TaskGraphServiceOptions);
    init(): Promise<ServiceResult<TaskIndexInfo>>;
    info(): Promise<ServiceResult<TaskIndexInfo>>;
    readIndex(): Promise<ServiceResult<TaskIndex>>;
    apply(request: TaskGraphApplyRequest): Promise<ServiceResult<TaskGraphApplyResult>>;
    listTasks(): Promise<ServiceResult<Record<string, TaskSummary>>>;
    showTask(taskId: string): Promise<ServiceResult<{
        task: TaskIndex["tasks"][string];
        projection: TaskGraphProjection["tasks"][string];
    }>>;
    actionable(): Promise<ServiceResult<{
        tasks: TaskGraphProjection["actionable"];
        order: string[];
    }>>;
    claim(options: ClaimTaskOptions): Promise<ServiceResult<{
        taskId: string;
        leaseId: string;
        expiresAt: string;
    }>>;
    renew(options: {
        taskId: string;
        leaseId: string;
        durationSeconds?: number;
    }): Promise<ServiceResult<{
        taskId: string;
        leaseId: string;
        expiresAt: string;
    }>>;
    release(options: {
        taskId: string;
        leaseId: string;
        control: TaskControlInput;
    }): Promise<ServiceResult<{
        taskId: string;
        phase: "idle";
    }>>;
    complete(options: CompleteTaskOptions): Promise<ServiceResult<{
        taskId: string;
        phase: "succeeded";
    }>>;
    fail(options: {
        taskId: string;
        leaseId: string;
        reason: string;
    }): Promise<ServiceResult<{
        taskId: string;
        phase: "failed";
    }>>;
    retry(options: {
        taskId: string;
        expectedRevision: number;
    }): Promise<ServiceResult<{
        taskId: string;
        phase: "idle";
    }>>;
    cancel(options: CancelTaskOptions): Promise<ServiceResult<{
        taskId: string;
        cancelledTaskIds: string[];
    }>>;
    removeTasks(options: RemoveTasksOptions): Promise<ServiceResult<{
        removedTaskIds: string[];
    }>>;
    private executionMutation;
}
