await import("./cli-generated.test.ts");
await import("./discard.test.ts");
await import("./index-query.test.ts");
await import("./parsing-directory.test.ts");
await import("./resources.test.ts");
await import("./scale.test.ts");
await import("./staging.test.ts");
await import("./relations.test.ts");
await import("./transaction.test.ts");
