/*
 * Generated investigation report checker TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/scripts/investigation-report/check-investigations.d.mts
 * Source path: scripts/investigation-report/check-investigations.d.mts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/investigation-report
 * Rebuild: bun run sync:investigation-report-check
 */
export type InvestigationReportStatus = "调查中" | "暂停" | "已结束";

export type InvestigationReportCheckOptions = {
  investigationsDir?: string;
  reports?: readonly string[];
  topics?: readonly string[];
  workspaceRoot: string;
};

export type InvestigationReportCheckResult = {
  availableReportCount: number;
  errors: string[];
  indexPath: string;
  selectedReportCount: number;
  topicCount: number;
};

export declare function runInvestigationReportCheckCli(
  argv?: readonly string[]
): Promise<number>;

export declare function validateInvestigationReports(
  options: InvestigationReportCheckOptions
): Promise<InvestigationReportCheckResult>;
