#!/usr/bin/env node
/*
 * Generated decision-records CLI. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/scripts/decision-records/src/cli.ts
 * Source path: scripts/decision-records/src/cli.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */

// scripts/decision-records/src/cli.ts
import fs2 from "node:fs/promises";
import path2 from "node:path";
import process2 from "node:process";
import { pathToFileURL } from "node:url";

// scripts/decision-records/src/markdown.ts
function extractInlineLinks(markdown) {
  const links = [];
  const pattern = /\[([^\]\r\n]+)\]\(([^)\r\n]+)\)/g;
  for (const match of markdown.matchAll(pattern)) {
    const matchIndex = match.index ?? 0;
    if (matchIndex > 0 && markdown[matchIndex - 1] === "!") {
      continue;
    }
    let target = match[2].trim();
    if (target.startsWith("<") && target.endsWith(">")) {
      target = target.slice(1, -1).trim();
    }
    links.push({
      label: match[1].trim(),
      target
    });
  }
  return links;
}
function stripLinkSuffix(target) {
  const hashIndex = target.indexOf("#");
  const queryIndex = target.indexOf("?");
  const indexes = [hashIndex, queryIndex].filter((value) => value >= 0);
  const endIndex = indexes.length > 0 ? Math.min(...indexes) : target.length;
  return target.slice(0, endIndex);
}
function parseSections(body) {
  const matches = [...body.matchAll(/^## ([^\n]+)$/gm)];
  return matches.map((match, index) => {
    const heading = "## " + match[1].trim();
    const headingIndex = match.index ?? 0;
    const lineEnd = body.indexOf(`
`, headingIndex);
    const contentStart = lineEnd >= 0 ? lineEnd + 1 : body.length;
    const contentEnd = index + 1 < matches.length ? matches[index + 1].index ?? body.length : body.length;
    return {
      content: body.slice(contentStart, contentEnd).trim(),
      heading,
      index: headingIndex
    };
  });
}
function fieldValues(sectionContent, label) {
  const escapedLabel = label.replace(/[.*+?^$()|[\]\\]/g, "\\$&");
  const pattern = new RegExp("^- " + escapedLabel + ":\\s*(.*?)\\s*$", "gm");
  return [...sectionContent.matchAll(pattern)].map((match) => match[1].trim());
}
function requireSingleField(relativePath, sectionContent, label, errors) {
  const values = fieldValues(sectionContent, label);
  if (values.length === 0) {
    errors.push(relativePath + ' must include field "- ' + label + ': <value>"');
    return null;
  }
  if (values.length > 1) {
    errors.push(relativePath + ' must include field "- ' + label + ':" exactly once');
  }
  if (values[0].length === 0) {
    errors.push(relativePath + ' field "- ' + label + ':" must not be empty');
    return null;
  }
  return values[0];
}
function requireNonEmptyField(relativePath, sectionContent, label, errors) {
  const values = fieldValues(sectionContent, label);
  if (values.length === 0 || values.every((value) => value.length === 0)) {
    errors.push(relativePath + ' must include non-empty field "- ' + label + ': <value>"');
  }
}

// scripts/decision-records/src/scan.ts
import fs from "node:fs/promises";
import path from "node:path";

// scripts/decision-records/src/types.ts
var decisionStatuses = [
  "active",
  "amended",
  "superseded",
  "invalidated"
];
var decisionStatusSet = new Set(decisionStatuses);

// scripts/decision-records/src/scan.ts
var requiredRootFiles = new Set([
  "decision-record-index.md",
  "decision-record-rules.md"
]);
var sectionOrder = [
  "## 状态",
  "## 问题",
  "## 背景与约束",
  "## 决策过程",
  "## 决定",
  "## 影响",
  "## 验证"
];
var requiredSections = new Set([
  "## 状态",
  "## 问题",
  "## 决定",
  "## 影响",
  "## 验证"
]);
var impactAreaPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
var decisionFilePattern = /^(\d{6})-([a-z]+)-([a-z0-9]+(?:-[a-z0-9]+)*)\.md$/;
var decisionRelativePathPattern = /^(?:archive\/)?[a-z0-9]+(?:-[a-z0-9]+)*\/\d{6}-[a-z]+-[a-z0-9]+(?:-[a-z0-9]+)*\.md$/;
async function pathExists(targetPath) {
  try {
    await fs.access(targetPath);
    return true;
  } catch {
    return false;
  }
}
function toPosix(targetPath) {
  return targetPath.split(path.sep).join("/");
}
function displayPath(workspaceRoot, targetPath) {
  const relativePath = path.relative(workspaceRoot, targetPath);
  if (relativePath === "") {
    return ".";
  }
  if (relativePath === ".." || relativePath.startsWith(".." + path.sep) || path.isAbsolute(relativePath)) {
    return targetPath;
  }
  return toPosix(relativePath);
}
function isInsideDirectory(parentPath, targetPath) {
  const relativePath = path.relative(parentPath, targetPath);
  return relativePath !== "" && relativePath !== ".." && !relativePath.startsWith(".." + path.sep) && !path.isAbsolute(relativePath);
}
function fullDateFromCompactPrefix(dateText) {
  const match = dateText.match(/^(\d{2})(\d{2})(\d{2})$/);
  if (!match) {
    return null;
  }
  const year = 2000 + Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const date = new Date(Date.UTC(year, month - 1, day));
  if (date.getUTCFullYear() !== year || date.getUTCMonth() !== month - 1 || date.getUTCDate() !== day) {
    return null;
  }
  return String(year) + "-" + match[2] + "-" + match[3];
}
function parseDecisionFileName(fileName) {
  const match = fileName.match(decisionFilePattern);
  if (!match) {
    return null;
  }
  return {
    datePrefix: match[1],
    status: match[2],
    titleSlug: match[3]
  };
}
async function validateDecisionLink(options) {
  const {
    baseDirectory,
    decisionsDirectory,
    errors,
    rawTarget,
    relativeSourcePath
  } = options;
  const target = stripLinkSuffix(rawTarget.trim());
  if (target.length === 0) {
    errors.push(relativeSourcePath + " decision link must target a file: " + rawTarget);
    return null;
  }
  if (/^[a-z][a-z0-9+.-]*:/i.test(target)) {
    errors.push(relativeSourcePath + " decision link must be relative: " + rawTarget);
    return null;
  }
  if (target.includes("\\") || path.isAbsolute(target)) {
    errors.push(relativeSourcePath + " decision link must use a relative POSIX path: " + rawTarget);
    return null;
  }
  const resolvedTarget = path.resolve(baseDirectory, target);
  if (!isInsideDirectory(decisionsDirectory, resolvedTarget)) {
    errors.push(relativeSourcePath + " decision link points outside the decision directory: " + rawTarget);
    return null;
  }
  const relativeTarget = toPosix(path.relative(decisionsDirectory, resolvedTarget));
  if (!decisionRelativePathPattern.test(relativeTarget)) {
    errors.push(relativeSourcePath + " decision link has an invalid target path: " + rawTarget);
    return null;
  }
  if (!await pathExists(resolvedTarget)) {
    errors.push(relativeSourcePath + " decision link target does not exist: " + rawTarget);
    return null;
  }
  return relativeTarget;
}
async function validateDecisionBody(options) {
  const {
    archived,
    body: rawBody,
    decisionPath,
    decisionsDirectory,
    fileName,
    relativePath,
    errors
  } = options;
  const body = rawBody.replace(/^\uFEFF/, "").replace(/\r\n/g, `
`);
  const parsedFileName = parseDecisionFileName(fileName);
  const datePrefix = parsedFileName?.datePrefix ?? fileName.slice(0, 6);
  const fileStatus = parsedFileName?.status;
  const fullDate = fullDateFromCompactPrefix(datePrefix);
  const expectedTitlePrefix = "# " + (fullDate ?? "YYYY-MM-DD") + " - ";
  const firstLine = body.split(`
`, 1)[0];
  const title = firstLine.startsWith(expectedTitlePrefix) ? firstLine.slice(expectedTitlePrefix.length).trim() : "";
  if (!parsedFileName) {
    errors.push(relativePath + " must use file name format YYMMDD-<status>-short-title.md");
  }
  if (!fullDate) {
    errors.push(relativePath + " has an invalid date prefix");
  }
  if (fileStatus && !decisionStatusSet.has(fileStatus)) {
    errors.push(relativePath + " has unsupported status " + fileStatus);
  }
  if (title.length === 0) {
    errors.push(relativePath + ' must start with "' + expectedTitlePrefix + '<标题>"');
  }
  if (fileStatus === "invalidated" && !archived) {
    errors.push(relativePath + " invalidated decisions must be stored under archive/<impact-area>/");
  }
  if (archived && fileStatus && fileStatus !== "invalidated") {
    errors.push(relativePath + " archive may contain only invalidated decisions");
  }
  const sections = parseSections(body);
  const sectionMap = new Map;
  const expectedSectionSet = new Set(sectionOrder);
  for (const section of sections) {
    if (!expectedSectionSet.has(section.heading)) {
      errors.push(relativePath + " has unsupported section " + section.heading);
      continue;
    }
    const existing = sectionMap.get(section.heading) ?? [];
    existing.push(section);
    sectionMap.set(section.heading, existing);
  }
  for (const sectionHeading of requiredSections) {
    if (!sectionMap.has(sectionHeading)) {
      errors.push(relativePath + " is missing section " + sectionHeading);
    }
  }
  for (const [sectionHeading, entries] of sectionMap) {
    if (entries.length > 1) {
      errors.push(relativePath + " contains section " + sectionHeading + " more than once");
    }
    for (const entry of entries) {
      if (entry.content.length === 0) {
        errors.push(relativePath + " section " + sectionHeading + " must not be empty");
      }
    }
  }
  let previousOrder = -1;
  for (const section of sections) {
    const currentOrder = sectionOrder.indexOf(section.heading);
    if (currentOrder < 0) {
      continue;
    }
    if (currentOrder < previousOrder) {
      errors.push(relativePath + " has sections out of order");
      break;
    }
    previousOrder = currentOrder;
  }
  let bodyStatus = null;
  const statusSection = sectionMap.get("## 状态")?.[0]?.content;
  if (statusSection) {
    bodyStatus = requireSingleField(relativePath, statusSection, "当前状态", errors);
    const cause = requireSingleField(relativePath, statusSection, "导致状态变化的决策", errors);
    requireSingleField(relativePath, statusSection, "状态说明", errors);
    if (bodyStatus && fileStatus && bodyStatus !== fileStatus) {
      errors.push(relativePath + " body status " + bodyStatus + " does not match file status " + fileStatus);
    }
    if (bodyStatus && !decisionStatusSet.has(bodyStatus)) {
      errors.push(relativePath + " body has unsupported status " + bodyStatus);
    }
    if (cause && fileStatus === "active" && cause !== "无") {
      errors.push(relativePath + ' active decisions must use "无" as status cause');
    }
    if (cause && fileStatus && fileStatus !== "active") {
      if (cause === "无") {
        errors.push(relativePath + " non-active decisions must link to the later decision");
      } else {
        const causeLinks = extractInlineLinks(cause);
        if (causeLinks.length === 0) {
          errors.push(relativePath + " non-active status cause must use an inline Markdown decision link");
        }
        for (const link of causeLinks) {
          const target = await validateDecisionLink({
            baseDirectory: path.dirname(decisionPath),
            decisionsDirectory,
            errors,
            rawTarget: link.target,
            relativeSourcePath: relativePath
          });
          if (target === relativePath) {
            errors.push(relativePath + " must not use itself as a status cause");
          }
        }
      }
    }
  }
  const decisionSection = sectionMap.get("## 决定")?.[0]?.content;
  if (decisionSection) {
    requireNonEmptyField(relativePath, decisionSection, "采用", errors);
    requireNonEmptyField(relativePath, decisionSection, "触发条件", errors);
  }
  return {
    bodyStatus,
    datePrefix,
    fileStatus,
    fullDate,
    title
  };
}
async function scanArea(options) {
  const {
    archived,
    areaId,
    areaPath,
    decisionsDirectory,
    errors,
    records
  } = options;
  const areaEntries = await fs.readdir(areaPath, { withFileTypes: true });
  areaEntries.sort((left, right) => left.name.localeCompare(right.name));
  const markdownFiles = areaEntries.filter((entry) => entry.isFile() && entry.name.endsWith(".md"));
  if (markdownFiles.length === 0) {
    errors.push((archived ? "Archived decision area" : "Decision impact area") + " must contain at least one decision file: " + areaId);
  }
  for (const entry of areaEntries) {
    const relativePath = toPosix(path.relative(decisionsDirectory, path.join(areaPath, entry.name)));
    if (entry.isDirectory()) {
      errors.push("Decision area must not contain nested directories: " + relativePath);
      continue;
    }
    if (!entry.isFile()) {
      errors.push("Decision area contains unsupported entry: " + relativePath);
      continue;
    }
    if (!entry.name.endsWith(".md")) {
      errors.push("Decision area must contain only Markdown files: " + relativePath);
      continue;
    }
    const decisionPath = path.join(areaPath, entry.name);
    const body = await fs.readFile(decisionPath, "utf8");
    const metadata = await validateDecisionBody({
      archived,
      body,
      decisionPath,
      decisionsDirectory,
      errors,
      fileName: entry.name,
      relativePath
    });
    records.push({
      archived,
      areaId,
      decisionPath,
      fileName: entry.name,
      relativePath,
      ...metadata
    });
  }
}
async function scanArchive(options) {
  const {
    archivePath,
    areaIds,
    decisionsDirectory,
    errors,
    records
  } = options;
  const archiveEntries = await fs.readdir(archivePath, { withFileTypes: true });
  archiveEntries.sort((left, right) => left.name.localeCompare(right.name));
  for (const entry of archiveEntries) {
    const entryPath = path.join(archivePath, entry.name);
    if (!entry.isDirectory()) {
      errors.push("docs/decisions/archive may contain only impact-area directories: " + entry.name);
      continue;
    }
    const areaId = entry.name;
    areaIds.add(areaId);
    if (!impactAreaPattern.test(areaId)) {
      errors.push("Archived decision impact area must use kebab-case: " + areaId);
    }
    await scanArea({
      archived: true,
      areaId,
      areaPath: entryPath,
      decisionsDirectory,
      errors,
      records
    });
  }
}
async function scanDecisionRecords(options = {}) {
  const workspaceRoot = path.resolve(options.workspaceRoot ?? process.cwd());
  const configuredDecisionDirectory = options.decisionsDir ?? "docs/decisions";
  const decisionsDirectory = path.isAbsolute(configuredDecisionDirectory) ? path.resolve(configuredDecisionDirectory) : path.resolve(workspaceRoot, configuredDecisionDirectory);
  const errors = [];
  const records = [];
  const areaIds = new Set;
  const decisionsLabel = displayPath(workspaceRoot, decisionsDirectory);
  const indexPath = path.join(decisionsDirectory, "decision-record-index.md");
  const rulesPath = path.join(decisionsDirectory, "decision-record-rules.md");
  const indexRelativePath = displayPath(workspaceRoot, indexPath);
  if (!await pathExists(decisionsDirectory)) {
    return {
      areaIds,
      decisionsDirectory,
      errors: [decisionsLabel + " is required"],
      index: "",
      indexPath,
      indexRelativePath,
      records,
      workspaceRoot
    };
  }
  const decisionsStat = await fs.stat(decisionsDirectory);
  if (!decisionsStat.isDirectory()) {
    return {
      areaIds,
      decisionsDirectory,
      errors: [decisionsLabel + " must be a directory"],
      index: "",
      indexPath,
      indexRelativePath,
      records,
      workspaceRoot
    };
  }
  if (!await pathExists(indexPath)) {
    errors.push(indexRelativePath + " is required");
  }
  if (!await pathExists(rulesPath)) {
    errors.push(displayPath(workspaceRoot, rulesPath) + " is required");
  }
  const index = await pathExists(indexPath) ? await fs.readFile(indexPath, "utf8") : "";
  const rootEntries = await fs.readdir(decisionsDirectory, { withFileTypes: true });
  rootEntries.sort((left, right) => left.name.localeCompare(right.name));
  for (const entry of rootEntries) {
    const entryPath = path.join(decisionsDirectory, entry.name);
    if (entry.isFile()) {
      if (!requiredRootFiles.has(entry.name)) {
        errors.push(decisionsLabel + " root contains unsupported file " + entry.name);
      }
      continue;
    }
    if (!entry.isDirectory()) {
      errors.push(decisionsLabel + " contains unsupported entry " + entry.name);
      continue;
    }
    if (entry.name === "archive") {
      await scanArchive({
        archivePath: entryPath,
        areaIds,
        decisionsDirectory,
        errors,
        records
      });
      continue;
    }
    const areaId = entry.name;
    areaIds.add(areaId);
    if (!impactAreaPattern.test(areaId)) {
      errors.push("Decision impact area must use kebab-case: " + areaId);
    }
    await scanArea({
      archived: false,
      areaId,
      areaPath: entryPath,
      decisionsDirectory,
      errors,
      records
    });
  }
  const backtick = String.fromCharCode(96);
  for (const areaId of [...areaIds].sort()) {
    if (!index.includes(backtick + areaId + backtick)) {
      errors.push(indexRelativePath + " must describe impact area " + areaId);
    }
  }
  return {
    areaIds,
    decisionsDirectory,
    errors,
    index,
    indexPath,
    indexRelativePath,
    records,
    workspaceRoot
  };
}

// scripts/decision-records/src/index.ts
var managedIndexHeadings = new Set([
  "## 活动决策",
  "## 决策清单"
]);
function renderActiveSection(records) {
  const groups = new Map;
  const activeRecords = records.filter((record) => record.fileStatus === "active" && !record.archived);
  for (const record of activeRecords) {
    const current = groups.get(record.areaId) ?? [];
    current.push(record);
    groups.set(record.areaId, current);
  }
  if (groups.size === 0) {
    return "当前没有 active 决策。";
  }
  const backtick = String.fromCharCode(96);
  const blocks = [];
  for (const areaId of [...groups.keys()].sort()) {
    const areaRecords = groups.get(areaId) ?? [];
    areaRecords.sort((left, right) => {
      const dateOrder = right.datePrefix.localeCompare(left.datePrefix);
      return dateOrder !== 0 ? dateOrder : left.fileName.localeCompare(right.fileName);
    });
    const lines = [backtick + areaId + backtick + "：", ""];
    for (let index = 0;index < areaRecords.length; index += 1) {
      const record = areaRecords[index];
      lines.push(`${index + 1}. [active: ${record.fullDate} - ${record.title}](${record.relativePath})`);
    }
    blocks.push(lines.join(`
`));
  }
  return blocks.join(`

`);
}
function expectedIndex(scan) {
  const index = scan.index.replace(/\r\n/g, `
`);
  const headings = parseSections(index).filter((section2) => managedIndexHeadings.has(section2.heading));
  const errors = [];
  let prefix;
  if (headings.length > 1) {
    errors.push(scan.indexRelativePath + " must contain only one managed decision-list section");
    return { errors, text: null };
  }
  if (headings.length === 0) {
    prefix = index.trimEnd();
  } else {
    const managed = headings[0];
    const laterHeadings = parseSections(index).filter((section2) => section2.index > managed.index);
    if (laterHeadings.length > 0) {
      errors.push(scan.indexRelativePath + " managed decision-list section must be the final section");
      return { errors, text: null };
    }
    prefix = index.slice(0, managed.index).trimEnd();
  }
  const section = renderActiveSection(scan.records);
  return {
    errors,
    text: prefix + `

## 活动决策

` + section + `
`
  };
}
async function validateDecisionRecords(options = {}) {
  const scan = await scanDecisionRecords(options);
  const errors = [...scan.errors];
  const generated = expectedIndex(scan);
  errors.push(...generated.errors);
  if (generated.text !== null && scan.index.replace(/\r\n/g, `
`) !== generated.text) {
    errors.push(scan.indexRelativePath + " active decision section is out of sync; run sync-index --write");
  }
  return {
    activeCount: scan.records.filter((record) => record.fileStatus === "active").length,
    archivedCount: scan.records.filter((record) => record.archived).length,
    areaCount: scan.areaIds.size,
    decisionCount: scan.records.length,
    errors,
    scan
  };
}

// scripts/decision-records/src/cli.ts
function usage() {
  return [
    "Usage:",
    "  node decision-records.mjs [check] [options]",
    "  node decision-records.mjs list [--all | --status <statuses>] [options]",
    "  node decision-records.mjs sync-index [--write] [options]",
    "",
    "Commands:",
    "  check       Validate directories, files, statuses, links, and the active index.",
    "  list        List active decisions by default. Use --all or --status for history.",
    "  sync-index  Check the generated active section. Use --write to update the index.",
    "",
    "Options:",
    "  --root <path>           Workspace root. Defaults to the current directory.",
    "  --decisions-dir <path>  Decision directory. Defaults to docs/decisions under --root.",
    "  --all                   Include all statuses with list.",
    "  --status <statuses>     Comma-separated statuses for list.",
    "  --write                 Apply sync-index changes to decision-record-index.md.",
    "  -h, --help              Show this help text.",
    "",
    "Exit codes: 0 success, 1 validation or index drift, 2 invalid arguments."
  ].join(`
`);
}
function parseArgs(argv) {
  const remaining = [...argv];
  let command = "check";
  let workspaceRoot = process2.cwd();
  let decisionsDir = "docs/decisions";
  let statusText = null;
  let all = false;
  let write = false;
  let help = false;
  if (remaining[0] && !remaining[0].startsWith("-")) {
    const candidate = remaining.shift();
    if (!candidate || !new Set(["check", "list", "sync-index"]).has(candidate)) {
      throw new Error("Unsupported command: " + candidate);
    }
    command = candidate;
  }
  for (let index = 0;index < remaining.length; index += 1) {
    const arg = remaining[index];
    if (arg === "-h" || arg === "--help") {
      help = true;
      continue;
    }
    if (arg === "--all") {
      all = true;
      continue;
    }
    if (arg === "--write") {
      write = true;
      continue;
    }
    if (arg === "--root" || arg === "--decisions-dir" || arg === "--status") {
      const value = remaining[index + 1];
      if (!value || value.startsWith("--")) {
        throw new Error(arg + " requires a value");
      }
      if (arg === "--root") {
        workspaceRoot = value;
      } else if (arg === "--decisions-dir") {
        decisionsDir = value;
      } else {
        statusText = value;
      }
      index += 1;
      continue;
    }
    throw new Error("Unsupported argument: " + arg);
  }
  if (command !== "list" && (all || statusText !== null)) {
    throw new Error("--all and --status are only valid with list");
  }
  if (command !== "sync-index" && write) {
    throw new Error("--write is only valid with sync-index");
  }
  if (all && statusText !== null) {
    throw new Error("Use either --all or --status, not both");
  }
  return {
    all,
    command,
    decisionsDir,
    help,
    statusText,
    workspaceRoot,
    write
  };
}
function selectedStatuses(args) {
  if (args.all) {
    return new Set(decisionStatuses);
  }
  if (args.statusText === null) {
    return new Set(["active"]);
  }
  const statuses = args.statusText.split(",").map((status) => status.trim()).filter((status) => status.length > 0);
  if (statuses.length === 0) {
    throw new Error("--status must include at least one status");
  }
  for (const status of statuses) {
    if (!decisionStatusSet.has(status)) {
      throw new Error("Unsupported decision status: " + status);
    }
  }
  return new Set(statuses);
}
function printErrors(errors) {
  console.error("Decision records command failed:");
  for (const error of errors) {
    console.error("- " + error);
  }
}
async function runCheck(args) {
  const result = await validateDecisionRecords({
    decisionsDir: args.decisionsDir,
    workspaceRoot: args.workspaceRoot
  });
  if (result.errors.length > 0) {
    printErrors(result.errors);
    return 1;
  }
  console.log("Decision records check passed (" + result.areaCount + " areas, " + result.decisionCount + " decisions, " + result.activeCount + " active, " + result.archivedCount + " archived).");
  return 0;
}
async function runList(args) {
  const scan = await scanDecisionRecords({
    decisionsDir: args.decisionsDir,
    workspaceRoot: args.workspaceRoot
  });
  if (scan.errors.length > 0) {
    printErrors(scan.errors);
    return 1;
  }
  const statuses = selectedStatuses(args);
  const records = scan.records.filter((record) => record.fileStatus !== undefined && statuses.has(record.fileStatus)).sort((left, right) => {
    const areaOrder = left.areaId.localeCompare(right.areaId);
    if (areaOrder !== 0) {
      return areaOrder;
    }
    const dateOrder = right.datePrefix.localeCompare(left.datePrefix);
    return dateOrder !== 0 ? dateOrder : left.fileName.localeCompare(right.fileName);
  });
  if (records.length === 0) {
    console.log("No decisions matched the selected statuses.");
    return 0;
  }
  for (const record of records) {
    console.log((record.fileStatus ?? "").padEnd(11) + " " + record.fullDate + " " + record.relativePath + " - " + record.title);
  }
  return 0;
}
async function runSyncIndex(args) {
  const scan = await scanDecisionRecords({
    decisionsDir: args.decisionsDir,
    workspaceRoot: args.workspaceRoot
  });
  if (scan.errors.length > 0) {
    printErrors(scan.errors);
    return 1;
  }
  const generated = expectedIndex(scan);
  if (generated.errors.length > 0 || generated.text === null) {
    printErrors(generated.errors);
    return 1;
  }
  const current = scan.index.replace(/\r\n/g, `
`);
  if (current === generated.text) {
    console.log("Active decision index is current.");
    return 0;
  }
  if (!args.write) {
    console.error("Active decision index is out of sync.");
    console.error("Run sync-index --write to update " + scan.indexRelativePath + ".");
    return 1;
  }
  await fs2.writeFile(scan.indexPath, generated.text, "utf8");
  console.log("Updated " + scan.indexRelativePath + " with active decisions.");
  return 0;
}
function isMainModule() {
  const entryPoint = process2.argv[1];
  return entryPoint !== undefined && pathToFileURL(path2.resolve(entryPoint)).href === import.meta.url;
}
async function main() {
  try {
    const args = parseArgs(process2.argv.slice(2));
    if (args.help) {
      console.log(usage());
      process2.exit(0);
    }
    let exitCode;
    if (args.command === "check") {
      exitCode = await runCheck(args);
    } else if (args.command === "list") {
      exitCode = await runList(args);
    } else {
      exitCode = await runSyncIndex(args);
    }
    process2.exit(exitCode);
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    console.error("");
    console.error(usage());
    process2.exit(2);
  }
}
if (isMainModule()) {
  await main();
}
export {
  validateDecisionRecords,
  scanDecisionRecords
};
