/*
 * Generated decision-records TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/scripts/decision-records/decision-records.d.mts
 * Source path: scripts/decision-records/decision-records.d.mts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
export type DecisionRelationType = "修订" | "替代" | "判定无效" | "归并";

export type DecisionStatus = "active" | "archived";

export type DecisionListStatus = DecisionStatus | "all";

export type DecisionAlignment = "aligned" | "unaligned";

export type DecisionListAlignment = DecisionAlignment | "all";

export type DecisionRelation = {
  target: string;
  type: DecisionRelationType;
};

export type DecisionProjection = {
  background: string;
  decision: string;
  purpose: string;
  relations: DecisionRelation[];
  title: string;
};

export type DecisionMetadata =
  | {
    alignment: "aligned";
    createdAt: string;
    status: "active";
  }
  | {
    alignment: "unaligned";
    createdAt: string;
    status: "active";
  }
  | {
    alignment: null;
    createdAt: string;
    status: "archived";
  };

export type DecisionDocument = DecisionProjection & DecisionMetadata;

export type DecisionIndexEntry = DecisionProjection & DecisionMetadata & {
  path: string;
};

export type DecisionIndex = {
  records: DecisionIndexEntry[];
  schemaVersion: 4;
};

export type DecisionRecord = {
  alignment: DecisionAlignment | null;
  areaId: string;
  bodyValid: boolean;
  createdAt: string | null;
  decisionPath: string;
  document: DecisionDocument | null;
  fileName: string;
  indexed: boolean;
  markdownExists: boolean;
  projection: DecisionProjection;
  relativePath: string;
  status: DecisionStatus | null;
};

export type DecisionScanOptions = {
  decisionsDir?: string;
  workspaceRoot?: string;
};

export type DecisionScan = {
  areaIds: Set<string>;
  decisionsDirectoryAvailable: boolean;
  decisionsDirectory: string;
  errors: string[];
  index: DecisionIndex | null;
  indexErrors: string[];
  indexExists: boolean;
  indexPath: string;
  indexRelativePath: string;
  indexText: string;
  records: DecisionRecord[];
  sourceErrors: string[];
  workspaceRoot: string;
};

export type DecisionValidationResult = {
  activeCount: number;
  alignedCount: number;
  archivedCount: number;
  areaCount: number;
  decisionCount: number;
  errors: string[];
  scan: DecisionScan;
  unalignedCount: number;
};

export declare function runDecisionRecordsCli(
  argv?: readonly string[]
): Promise<number>;

export declare function scanDecisionRecords(
  options?: DecisionScanOptions
): Promise<DecisionScan>;

export declare function validateDecisionRecords(
  options?: DecisionScanOptions
): Promise<DecisionValidationResult>;
