/*
 * Generated decision-records TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/scripts/decision-records/decision-records.d.mts
 * Source path: scripts/decision-records/decision-records.d.mts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/decision-records
 * Rebuild: bun run sync:decision-records-cli
 */
export type DecisionRelationType = "修订" | "替代" | "判定无效" | "归并";

export type DecisionRelation = {
  target: string;
  type: DecisionRelationType;
};

export type DecisionIndexEntry = {
  background: string;
  decision: string;
  path: string;
  purpose: string;
  title: string;
};

export type DecisionIndex = {
  current: DecisionIndexEntry[];
  schemaVersion: 2;
};

export type DecisionRecord = {
  archived: boolean;
  areaId: string;
  background: string;
  bodyValid: boolean;
  current: boolean;
  datePrefix: string;
  decision: string;
  decisionPath: string;
  fileName: string;
  fullDate: string | null;
  purpose: string;
  relations: DecisionRelation[];
  relativePath: string;
  title: string;
};

export type DecisionScanOptions = {
  decisionsDir?: string;
  workspaceRoot?: string;
};

export type DecisionScan = {
  areaIds: Set<string>;
  currentPaths: Set<string>;
  decisionsDirectoryAvailable: boolean;
  decisionsDirectory: string;
  errors: string[];
  index: DecisionIndex | null;
  indexExists: boolean;
  indexPath: string;
  indexRelativePath: string;
  indexText: string;
  records: DecisionRecord[];
  workspaceRoot: string;
};

export type DecisionValidationResult = {
  archivedCount: number;
  areaCount: number;
  currentCount: number;
  decisionCount: number;
  errors: string[];
  scan: DecisionScan;
};

export declare function runDecisionRecordsCli(
  argv?: readonly string[]
): Promise<number>;

export declare function scanDecisionRecords(
  options?: DecisionScanOptions
): Promise<DecisionScan>;

export declare function validateDecisionRecords(
  options?: DecisionScanOptions
): Promise<DecisionValidationResult>;
