import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { parseArgs, promisify } from "node:util";
import { pathExists } from "./filesystem.ts";

export type GeneratedFileMode = "check" | "write";

export type BunBundleOptions = {
  cwd: string;
  entryPath: string;
  format: "cjs" | "esm";
  minify?: boolean;
};

export type GeneratedFileHeaderOptions = {
  additionalLines?: string[];
  artifactName: string;
  rebuildCommand: string;
  repository: string;
  skillSourcePath?: string;
  sourcePath: string;
};

const execFileAsync = promisify(execFile);

export function parseGeneratedFileMode(argv: string[]): GeneratedFileMode {
  const { values } = parseArgs({
    args: argv,
    options: {
      check: { type: "boolean" },
      write: { type: "boolean" }
    },
    strict: true
  });
  if (values.check && values.write) {
    throw new Error("--check and --write cannot be used together");
  }

  return values.write ? "write" : "check";
}

export async function bundleWithBun(options: BunBundleOptions): Promise<string> {
  const tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "skills-bundle-"));
  const outputPath = path.join(tempDir, `bundle.${options.format === "cjs" ? "cjs" : "mjs"}`);
  const args = [
    "build",
    options.entryPath,
    "--target=node",
    `--format=${options.format}`,
    "--packages=bundle",
    ...(options.minify ? ["--minify"] : []),
    `--outfile=${outputPath}`
  ];

  try {
    await execFileAsync(process.execPath, args, { cwd: options.cwd });
    const bundled = await fs.readFile(outputPath, "utf8");
    return bundled.startsWith("#!") ? bundled : `#!/usr/bin/env node\n${bundled}`;
  } finally {
    await fs.rm(tempDir, { force: true, recursive: true });
  }
}

export async function syncGeneratedFile(
  outputPath: string,
  expected: string,
  mode: GeneratedFileMode
): Promise<"current" | "stale" | "written"> {
  if (await pathExists(outputPath) && await fs.readFile(outputPath, "utf8") === expected) {
    return "current";
  }

  if (mode === "check") {
    return "stale";
  }

  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, expected, "utf8");
  return "written";
}

export function addGeneratedFileHeader(
  content: string,
  options: GeneratedFileHeaderOptions
): string {
  const repositoryUrl = `https://github.com/${options.repository}`;
  const headerLines = [
    "/*",
    ` * Generated ${options.artifactName}. Do not edit this file directly.`,
    ` * Repository: ${repositoryUrl}`,
    ` * Maintained source: ${repositoryUrl}/blob/main/${options.sourcePath}`,
    ` * Source path: ${options.sourcePath}`,
    ...(options.skillSourcePath === undefined
      ? []
      : [` * Skill source directory: ${repositoryUrl}/tree/main/${options.skillSourcePath}`]),
    ` * Rebuild: ${options.rebuildCommand}`,
    ...(options.additionalLines ?? []).map((line) => ` * ${line}`),
    " */",
    ""
  ];
  const header = headerLines.join("\n");

  if (!content.startsWith("#!")) {
    return `${header}${content}`;
  }

  const firstLineEnd = content.indexOf("\n");
  if (firstLineEnd === -1) {
    return `${content}\n${header}`;
  }

  return `${content.slice(0, firstLineEnd + 1)}${header}${content.slice(firstLineEnd + 1)}`;
}
