export type GeneratedFileHeaderOptions = Readonly<{
  additionalLines?: readonly string[];
  artifactName: string;
  rebuildCommand: string;
  repository: string;
  skillSourcePath?: string;
  sourcePath: string;
}>;

export function buildGeneratedFileHeader(
  options: GeneratedFileHeaderOptions
): string {
  const repositoryUrl = `https://github.com/${options.repository}`;
  const headerLines = [
    "/*",
    ` * Generated ${options.artifactName}. Do not edit this file directly.`,
    ` * Repository: ${repositoryUrl}`,
    ` * Maintained source: ${repositoryUrl}/blob/main/${options.sourcePath}`,
    ` * Source path: ${options.sourcePath}`,
    ...(options.skillSourcePath === undefined
      ? []
      : [
          ` * Skill source directory: ${repositoryUrl}/tree/main/${options.skillSourcePath}`
        ]),
    ` * Rebuild: ${options.rebuildCommand}`,
    ...(options.additionalLines ?? []).map((line) => ` * ${line}`),
    " */"
  ];
  return headerLines.join("\n");
}
