export type GeneratedFileHeaderOptions = {
  additionalLines?: string[];
  artifactName: string;
  rebuildCommand: string;
  repositoryUrl: string;
  skillSourceUrl?: string;
  sourcePath: string;
  sourceUrl: string;
};

export function addGeneratedFileHeader(
  content: string,
  options: GeneratedFileHeaderOptions
): string {
  const headerLines = [
    "/*",
    ` * Generated ${options.artifactName}. Do not edit this file directly.`,
    ` * Repository: ${options.repositoryUrl}`,
    ` * Maintained source: ${options.sourceUrl}`,
    ` * Source path: ${options.sourcePath}`,
    ...(options.skillSourceUrl === undefined
      ? []
      : [` * Skill source directory: ${options.skillSourceUrl}`]),
    ` * Rebuild: ${options.rebuildCommand}`,
    ...(options.additionalLines ?? []).map((line) => ` * ${line}`),
    " */",
    ""
  ];
  const header = headerLines.join("\n");

  if (!content.startsWith("#!")) {
    return `${header}${content}`;
  }

  const firstLineEnd = content.indexOf("\n");
  if (firstLineEnd === -1) {
    return `${content}\n${header}`;
  }

  return `${content.slice(0, firstLineEnd + 1)}${header}${content.slice(firstLineEnd + 1)}`;
}
