/*
 * Generated skill structure validator TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/skill-validator/api/validate-skill.d.mts
 * Source path: tools/skill-validator/api/validate-skill.d.mts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/skill-maintainer
 * Rebuild: bun run sync:skill-validator
 */
export type SkillStructureValidationOptions = {
  allowedFrontmatterKeys?: readonly string[];
};

export type SkillStructureValidationResult = {
  errors: string[];
  markdownFileCount: number;
  skillDirectory: string;
};

export declare function runSkillValidatorCli(
  argv?: readonly string[]
): Promise<number>;

export declare function validateSkillDirectory(
  directory: string,
  options?: SkillStructureValidationOptions
): Promise<SkillStructureValidationResult>;
