/*
 * Generated verification catalog CLI TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/verification-evidence/api/verification-catalog.d.mts
 * Source path: tools/verification-evidence/api/verification-catalog.d.mts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/verification-implementation-review
 * Rebuild: bun run sync:verification-evidence-cli
 */
import type { VerificationCaseShowResult } from "./verification-case-show-result.types.mjs";
import type { VerificationEvidenceConfig } from "./verification-evidence-config.types.mjs";
import type { VerificationEvidenceIndexSyncResult } from "./verification-evidence-index-sync-result.types.mjs";
import type { VerificationEvidenceQueryResult } from "./verification-evidence-query-result.types.mjs";
import type { VerificationEvidenceReport } from "./verification-evidence-report.types.mjs";
import type { VerificationEvidenceStateIndex } from "./verification-evidence-state-index.types.mjs";

export type StandardOutputSchema<T> = {
  readonly "~standard": {
    readonly types?: { readonly input: unknown; readonly output: T };
    readonly validate: (value: unknown) => unknown;
  };
};

export type ValidateVerificationEvidenceOptions = {
  config?: unknown;
  configPath?: string;
  workspaceRoot: string;
};

export type QueryVerificationEvidenceOptions = {
  config?: unknown;
  configPath?: string;
  limit?: number;
  offset?: number;
  query?: string;
  verification?: "test" | "check" | "all";
  workspaceRoot: string;
};

export type ShowVerificationCaseOptions = {
  caseId: string;
  config?: unknown;
  configPath?: string;
  workspaceRoot: string;
};

export type SyncVerificationEvidenceIndexOptions = {
  config?: unknown;
  configPath?: string;
  mode: "check" | "write";
  workspaceRoot: string;
};

export type VerificationCaseState =
  VerificationEvidenceQueryResult["cases"][number];

export type {
  VerificationCaseShowResult,
  VerificationEvidenceConfig,
  VerificationEvidenceIndexSyncResult,
  VerificationEvidenceQueryResult,
  VerificationEvidenceReport,
  VerificationEvidenceStateIndex
};

export declare const verificationCaseShowResultSchema:
  StandardOutputSchema<VerificationCaseShowResult>;
export declare const verificationEvidenceConfigSchema:
  StandardOutputSchema<unknown>;
export declare const verificationEvidenceIndexSyncResultSchema:
  StandardOutputSchema<VerificationEvidenceIndexSyncResult>;
export declare const verificationEvidenceQueryResultSchema:
  StandardOutputSchema<VerificationEvidenceQueryResult>;
export declare const verificationEvidenceReportSchema:
  StandardOutputSchema<VerificationEvidenceReport>;
export declare const verificationEvidenceStateIndexSchema:
  StandardOutputSchema<VerificationEvidenceStateIndex>;

export declare function queryVerificationEvidence(
  options: QueryVerificationEvidenceOptions
): Promise<VerificationEvidenceQueryResult>;

export declare function showVerificationCase(
  options: ShowVerificationCaseOptions
): Promise<VerificationCaseShowResult>;

export declare function syncVerificationEvidenceIndex(
  options: SyncVerificationEvidenceIndexOptions
): Promise<VerificationEvidenceIndexSyncResult>;

export declare function validateVerificationEvidence(
  options: ValidateVerificationEvidenceOptions
): Promise<VerificationEvidenceReport>;

export declare function runVerificationCatalogCli(
  argv?: readonly string[]
): Promise<number>;
