/*
 * Generated VerificationEvidenceReport schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/verification-evidence/src/schemas.ts
 * Source path: tools/verification-evidence/src/schemas.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/verification-implementation-review
 * Rebuild: bun run sync:verification-evidence-cli
 */
export interface VerificationEvidenceReport {
  diagnostics: {
    blocking: boolean;
    caseId?: string;
    category: "catalog" | "config" | "index";
    code: string;
    column?: number;
    line?: number;
    message: string;
    path?: string;
    severity: "error" | "warning";
  }[];
  schemaVersion: 1;
  summary: {
    catalogCases: number;
    checkCases: number;
    testCases: number;
  };
}
