export const expectedSemanticChecks: readonly (readonly [
  checkId: string,
  command: "bun" | "node",
  commandPath: string
])[] = [
  [
    "test:change-plan:artifact-and-active-plan-gates",
    "bun",
    "./tools/change-plan/tests/checks/artifact-and-active-plan-gates.ts"
  ],
  [
    "test:change-plan:lifecycle-finalize",
    "bun",
    "./tools/change-plan/tests/checks/lifecycle-finalize.ts"
  ],
  [
    "test:change-plan:public-distribution",
    "bun",
    "./tools/change-plan/tests/checks/public-distribution.ts"
  ],
  [
    "test:decision-records:record-and-established-graph",
    "bun",
    "./tools/decision-records/tests/checks/record-and-established-graph.ts"
  ],
  [
    "test:decision-records:query-and-index-projection",
    "bun",
    "./tools/decision-records/tests/checks/query-and-index-projection.ts"
  ],
  [
    "test:decision-records:lifecycle-and-recovery",
    "bun",
    "./tools/decision-records/tests/checks/lifecycle-and-recovery.ts"
  ],
  [
    "test:decision-records:pending-stage",
    "bun",
    "./tools/decision-records/tests/stage.test.ts"
  ],
  [
    "test:decision-records:public-distribution",
    "bun",
    "./tools/decision-records/tests/checks/public-distribution.ts"
  ],
  [
    "test:investigation-report:collection-and-resources",
    "bun",
    "./tools/investigation-report/tests/checks/collection-and-resources.ts"
  ],
  [
    "test:investigation-report:index-and-query",
    "bun",
    "./tools/investigation-report/tests/checks/index-and-query.ts"
  ],
  [
    "test:investigation-report:transactional-maintenance",
    "bun",
    "./tools/investigation-report/tests/checks/transactional-maintenance.ts"
  ],
  [
    "test:investigation-report:pending-stage",
    "bun",
    "./tools/investigation-report/tests/checks/pending-stage.ts"
  ],
  [
    "test:investigation-report:cli-contract",
    "bun",
    "./tools/investigation-report/tests/checks/cli-contract.ts"
  ],
  [
    "test:task-graph:index-and-projection",
    "bun",
    "./tools/task-graph/tests/checks/index-and-projection.ts"
  ],
  [
    "test:task-graph:task-lifecycle",
    "bun",
    "./tools/task-graph/tests/checks/task-lifecycle.ts"
  ],
  [
    "test:task-graph:runtime-and-store",
    "bun",
    "./tools/task-graph/tests/checks/runtime-and-store.ts"
  ],
  [
    "test:task-graph:native-store",
    "node",
    "./tools/task-graph/tests/native-store.test.ts"
  ],
  [
    "test:task-graph:cli-rendering",
    "bun",
    "./tools/task-graph/tests/checks/cli-rendering.ts"
  ],
  [
    "test:task-graph:pending-stage",
    "bun",
    "./tools/task-graph/tests/staging.test.ts"
  ],
  [
    "test:task-graph:public-distribution",
    "bun",
    "./tools/task-graph/tests/checks/public-distribution.ts"
  ],
  [
    "test:task-graph:portable-build",
    "bun",
    "./tools/task-graph/tests/portable-build.test.ts"
  ],
  [
    "test:test-evidence:case-runtime",
    "bun",
    "./tools/test-evidence/tests/core.test.ts"
  ],
  [
    "test:test-evidence:public-boundary",
    "bun",
    "./tools/test-evidence/tests/public-boundary.test.ts"
  ],
  [
    "test:test-evidence:project-snapshot",
    "bun",
    "./scripts/test-evidence/snapshot.test.ts"
  ],
  [
    "test:test-evidence:project-reference-check",
    "bun",
    "./scripts/test-evidence/check.test.ts"
  ],
  [
    "test:test-evidence:migration",
    "bun",
    "./scripts/test-evidence/migrate.test.ts"
  ]
] as const;

export const expectedSemanticPrerequisites = new Map<string, readonly string[]>(
  [
    ["test:change-plan:public-distribution", ["script:check:change-plan-cli"]],
    [
      "test:decision-records:public-distribution",
      ["script:check:decision-records-cli"]
    ],
    ["test:task-graph:public-distribution", ["script:check:task-graph-cli"]]
  ]
);
