export const expectedSemanticGateChecks = [
  [
    undefined,
    "test:change-plan:artifact-and-active-plan-gates",
    "bun",
    [
      "./tools/change-plan/tests/markdown.test.ts",
      "./tools/change-plan/tests/metadata.test.ts",
      "./tools/change-plan/tests/check.test.ts",
      "./tools/change-plan/tests/git-distance.test.ts",
      "./tools/change-plan/tests/catalog.test.ts"
    ]
  ],
  [
    undefined,
    "test:change-plan:lifecycle-complete",
    "bun",
    [
      "./tools/change-plan/tests/lifecycle.test.ts",
      "./tools/change-plan/tests/complete.test.ts"
    ]
  ],
  [
    undefined,
    "test:change-plan:public-distribution",
    "bun",
    [
      "./tools/change-plan/tests/cli.test.ts",
      "./tools/change-plan/tests/generated-artifacts.test.ts"
    ]
  ],
  [
    undefined,
    "test:decision-records:record-and-established-graph",
    "bun",
    [
      "./tools/decision-records/tests/metadata.test.ts",
      "./tools/decision-records/tests/body-field-validation.test.ts",
      "./tools/decision-records/tests/type-path-invariants.test.ts",
      "./tools/decision-records/tests/record-guards.test.ts",
      "./tools/decision-records/tests/layout-index.test.ts",
      "./tools/decision-records/tests/relation-validation.test.ts",
      "./tools/decision-records/tests/trace-event-admission.test.ts",
      "./tools/decision-records/tests/state-snapshot.test.ts",
      "./tools/decision-records/tests/configured-decision-directory.test.ts",
      "./tools/decision-records/tests/filesystem-boundaries.test.ts"
    ]
  ],
  [
    undefined,
    "test:decision-records:query-and-index-projection",
    "bun",
    [
      "./tools/decision-records/tests/first-establishment.test.ts",
      "./tools/decision-records/tests/index-maintenance.test.ts",
      "./tools/decision-records/tests/list-facets.test.ts",
      "./tools/decision-records/tests/queries.test.ts",
      "./tools/decision-records/tests/cli-output-trace.test.ts"
    ]
  ],
  [
    undefined,
    "test:decision-records:lifecycle-and-recovery",
    "bun",
    [
      "./tools/decision-records/tests/activation-archive.test.ts",
      "./tools/decision-records/tests/candidate-lifecycle.test.ts",
      "./tools/decision-records/tests/candidate-scaffold.test.ts",
      "./tools/decision-records/tests/evolution.test.ts",
      "./tools/decision-records/tests/lifecycle-relations.test.ts",
      "./tools/decision-records/tests/rename.test.ts",
      "./tools/decision-records/tests/transaction-recovery.test.ts",
      "./tools/decision-records/tests/unrecorded-history.test.ts"
    ]
  ],
  [
    undefined,
    "test:decision-records:pending-stage",
    "bun",
    ["./tools/decision-records/tests/stage.test.ts"]
  ],
  [
    undefined,
    "test:decision-records:public-distribution",
    "bun",
    [
      "./tools/decision-records/tests/cli-args.test.ts",
      "./tools/decision-records/tests/generated-artifacts.test.ts"
    ]
  ],
  [
    undefined,
    "test:investigation-report:collection-and-resources",
    "bun",
    [
      "./tools/investigation-report/tests/candidate.test.ts",
      "./tools/investigation-report/tests/parsing-directory.test.ts",
      "./tools/investigation-report/tests/resources.test.ts",
      "./tools/investigation-report/tests/relations.test.ts"
    ]
  ],
  [
    undefined,
    "test:investigation-report:index-and-query",
    "bun",
    [
      "./tools/investigation-report/tests/index-query.test.ts",
      "./tools/investigation-report/tests/index-reader.test.ts",
      "./tools/investigation-report/tests/index-relations.test.ts",
      "./tools/investigation-report/tests/index-search.test.ts",
      "./tools/investigation-report/tests/index-selectors.test.ts",
      "./tools/investigation-report/tests/index-state.test.ts",
      "./tools/investigation-report/tests/list-facets.test.ts"
    ]
  ],
  [
    undefined,
    "test:investigation-report:transactional-maintenance",
    "bun",
    [
      "./tools/investigation-report/tests/transaction.test.ts",
      "./tools/investigation-report/tests/transaction-recovery.test.ts",
      "./tools/investigation-report/tests/transaction-sync.test.ts",
      "./tools/investigation-report/tests/discard.test.ts",
      "./tools/investigation-report/tests/publish.test.ts",
      "./tools/investigation-report/tests/rename.test.ts",
      "./tools/investigation-report/tests/rename-drift.test.ts",
      "./tools/investigation-report/tests/rename-recovery.test.ts",
      "./tools/investigation-report/tests/rename-validation.test.ts"
    ]
  ],
  [
    undefined,
    "test:investigation-report:pending-stage",
    "bun",
    ["./tools/investigation-report/tests/staging.test.ts"]
  ],
  [
    undefined,
    "test:investigation-report:cli-contract",
    "bun",
    [
      "./tools/investigation-report/tests/cli-generated.test.ts",
      "./tools/investigation-report/tests/cli-index.test.ts",
      "./tools/investigation-report/tests/cli-stage.test.ts"
    ]
  ],
  [
    undefined,
    "test:task-graph:index-and-projection",
    "bun",
    [
      "./tools/task-graph/tests/schema-index.test.ts",
      "./tools/task-graph/tests/graph-projection.test.ts"
    ]
  ],
  [
    undefined,
    "test:task-graph:task-lifecycle",
    "bun",
    [
      "./tools/task-graph/tests/lifecycle.test.ts",
      "./tools/task-graph/tests/task-removal.test.ts"
    ]
  ],
  [
    undefined,
    "test:task-graph:runtime-and-store",
    "bun",
    [
      "./tools/task-graph/tests/runtime.test.ts",
      "./tools/task-graph/tests/store.test.ts"
    ]
  ],
  [
    undefined,
    "test:task-graph:native-store",
    "node",
    ["./tools/task-graph/tests/native-store.test.ts"]
  ],
  [
    undefined,
    "test:task-graph:cli-rendering",
    "bun",
    [
      "./tools/task-graph/tests/cli.test.ts",
      "./tools/task-graph/tests/task-list-renderer.test.ts"
    ]
  ],
  [
    undefined,
    "test:task-graph:pending-stage",
    "bun",
    ["./tools/task-graph/tests/staging.test.ts"]
  ],
  [
    undefined,
    "test:task-graph:public-distribution",
    "bun",
    [
      "./tools/task-graph/tests/generated-artifacts.test.ts",
      "./tools/task-graph/tests/generated-artifacts-distribution.test.ts"
    ]
  ],
  [
    undefined,
    "test:task-graph:portable-build",
    "bun",
    ["./tools/task-graph/tests/portable-build.test.ts"]
  ],
  [
    undefined,
    "test:test-evidence:case-runtime",
    "bun",
    ["./tools/test-evidence/tests/core.test.ts"]
  ],
  [
    undefined,
    "test:test-evidence:public-boundary",
    "bun",
    ["./tools/test-evidence/tests/public-boundary.test.ts"]
  ],
  [
    undefined,
    "test:test-evidence:project-snapshot",
    "bun",
    ["./scripts/test-evidence/snapshot.test.ts"]
  ],
  [
    undefined,
    "test:test-evidence:project-reference-check",
    "bun",
    ["./scripts/test-evidence/check.test.ts"]
  ],
  [
    undefined,
    "test:test-evidence:migration",
    "bun",
    ["./scripts/test-evidence/migrate.test.ts"]
  ]
] as const;

export const expectedSemanticCommandPaths = new Map<string, string>([
  [
    "test:change-plan:artifact-and-active-plan-gates",
    "./tools/change-plan/tests/checks/artifact-and-active-plan-gates.ts"
  ],
  [
    "test:change-plan:lifecycle-complete",
    "./tools/change-plan/tests/checks/lifecycle-complete.ts"
  ],
  [
    "test:change-plan:public-distribution",
    "./tools/change-plan/tests/checks/public-distribution.ts"
  ],
  [
    "test:decision-records:record-and-established-graph",
    "./tools/decision-records/tests/checks/record-and-established-graph.ts"
  ],
  [
    "test:decision-records:query-and-index-projection",
    "./tools/decision-records/tests/checks/query-and-index-projection.ts"
  ],
  [
    "test:decision-records:lifecycle-and-recovery",
    "./tools/decision-records/tests/checks/lifecycle-and-recovery.ts"
  ],
  [
    "test:decision-records:pending-stage",
    "./tools/decision-records/tests/stage.test.ts"
  ],
  [
    "test:decision-records:public-distribution",
    "./tools/decision-records/tests/checks/public-distribution.ts"
  ],
  [
    "test:investigation-report:collection-and-resources",
    "./tools/investigation-report/tests/checks/collection-and-resources.ts"
  ],
  [
    "test:investigation-report:index-and-query",
    "./tools/investigation-report/tests/checks/index-and-query.ts"
  ],
  [
    "test:investigation-report:transactional-maintenance",
    "./tools/investigation-report/tests/checks/transactional-maintenance.ts"
  ],
  [
    "test:investigation-report:pending-stage",
    "./tools/investigation-report/tests/staging.test.ts"
  ],
  [
    "test:investigation-report:cli-contract",
    "./tools/investigation-report/tests/checks/cli-contract.ts"
  ],
  [
    "test:task-graph:index-and-projection",
    "./tools/task-graph/tests/checks/index-and-projection.ts"
  ],
  [
    "test:task-graph:task-lifecycle",
    "./tools/task-graph/tests/checks/task-lifecycle.ts"
  ],
  [
    "test:task-graph:runtime-and-store",
    "./tools/task-graph/tests/checks/runtime-and-store.ts"
  ],
  [
    "test:task-graph:native-store",
    "./tools/task-graph/tests/native-store.test.ts"
  ],
  [
    "test:task-graph:cli-rendering",
    "./tools/task-graph/tests/checks/cli-rendering.ts"
  ],
  ["test:task-graph:pending-stage", "./tools/task-graph/tests/staging.test.ts"],
  [
    "test:task-graph:public-distribution",
    "./tools/task-graph/tests/checks/public-distribution.ts"
  ],
  [
    "test:task-graph:portable-build",
    "./tools/task-graph/tests/portable-build.test.ts"
  ],
  [
    "test:test-evidence:case-runtime",
    "./tools/test-evidence/tests/core.test.ts"
  ],
  [
    "test:test-evidence:public-boundary",
    "./tools/test-evidence/tests/public-boundary.test.ts"
  ],
  [
    "test:test-evidence:project-snapshot",
    "./scripts/test-evidence/snapshot.test.ts"
  ],
  [
    "test:test-evidence:project-reference-check",
    "./scripts/test-evidence/check.test.ts"
  ],
  ["test:test-evidence:migration", "./scripts/test-evidence/migrate.test.ts"]
]);

export const expectedSemanticPrerequisites = new Map<string, readonly string[]>(
  [
    ["test:change-plan:public-distribution", ["script:check:change-plan-cli"]],
    [
      "test:decision-records:public-distribution",
      ["script:check:decision-records-cli"]
    ],
    ["test:task-graph:public-distribution", ["script:check:task-graph-cli"]]
  ]
);
