await import("../metadata.test.ts");
await import("../body-field-validation.test.ts");
await import("../type-path-invariants.test.ts");
await import("../record-guards.test.ts");
await import("../layout-index.test.ts");
await import("../relation-validation.test.ts");
await import("../state-snapshot.test.ts");
await import("../configured-decision-directory.test.ts");
await import("../filesystem-boundaries.test.ts");
