/*
 * Generated TestEvidenceReport schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/src/core-schemas.ts
 * Source path: tools/test-evidence/src/core-schemas.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/test-evidence-review
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface TestEvidenceReport {
  schemaVersion: 6;
  diagnostics: {
    blocking: boolean;
    category: "case" | "snapshot" | "reference" | "index" | "query";
    code: string;
    message: string;
    path?: string;
    caseId?: string;
    testId?: string;
  }[];
  casePath: "docs/test-evidence/cases";
  indexPath: "docs/test-evidence/test-evidence-index.json";
  sourceRevision: {
    entries: {
      [k: string]: string;
    };
    metadata: string;
  } | null;
  summary: {
    cases: number;
    tags: number;
    references: number;
  };
}
