/*
 * Generated TestEvidenceInspection schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/src/schemas.ts
 * Source path: tools/test-evidence/src/schemas.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/test-evidence-review
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface TestEvidenceInspection {
  cases: {
    codePath: string | null;
    contract: string[];
    id: string;
    lastReview: {
      at: string;
      commit: string;
      result: "pass" | "findings" | "blocked";
    } | null;
    line: number;
    proves: string[];
    reason: string[];
    review: string[];
    risk: string[];
    scope: string[];
    sourceMarkers: {
      attached: boolean;
      entryColumn: number | null;
      entryLine: number | null;
      markerLine: number;
      path: string;
      role: "main" | "derived" | "exempt";
    }[];
    status: ("active" | "planned") | null;
    title: string;
    trigger: {
      caseId: string;
      paths: string[];
      reasons: string[];
    } | null;
    valid: boolean;
    verification: ("automated" | "review" | "exempt") | null;
  }[];
  catalogAvailable: boolean;
  catalogPath: string;
  configPath: string;
  configurationValid: boolean;
  inventoryAvailable: boolean;
  report: {
    diagnostics: {
      blocking: boolean;
      caseId?: string;
      category:
        "catalog" | "config" | "discovery" | "git" | "inventory" | "mapping" | "review";
      code: string;
      column?: number;
      detectorId?: string;
      line?: number;
      message: string;
      path?: string;
      severity: "error" | "warning";
    }[];
    reviewTriggers: {
      caseId: string;
      paths: string[];
      reasons: string[];
    }[];
    schemaVersion: 2;
    summary: {
      activeAutomatedCases: number;
      catalogCases: number;
      derivedMarkers: number;
      discoveredTestEntries: number;
      discoveredTestFiles: number;
      exemptCases: number;
      exemptMarkers: number;
      exemptTestEntries: number;
      mainMarkers: number;
      plannedAutomatedCases: number;
      reviewCases: number;
      reviewTriggers: number;
      unregisteredTestEntries: number;
    };
  };
  schemaVersion: 2;
  sourceEntries: {
    column: number;
    detectorIds: string[];
    id: string;
    language: string;
    line: number;
    markers: {
      caseId: string;
      markerLine: number;
      role: "main" | "derived" | "exempt";
    }[];
    path: string;
  }[];
}
