/*
 * Generated TestEvidenceReport schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/scripts/test-evidence/src/schemas.ts
 * Source path: scripts/test-evidence/src/schemas.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/test-evidence-review
 * Rebuild: bun run sync:test-evidence-cli
 */
export interface TestEvidenceReport {
  diagnostics: {
    blocking: boolean;
    caseId?: string;
    category:
      "catalog" | "config" | "discovery" | "git" | "inventory" | "mapping" | "review";
    code: string;
    column?: number;
    detectorId?: string;
    line?: number;
    message: string;
    path?: string;
    severity: "error" | "warning";
  }[];
  reviewTriggers: {
    caseId: string;
    paths: string[];
    reasons: string[];
  }[];
  schemaVersion: 2;
  summary: {
    activeAutomatedCases: number;
    catalogCases: number;
    derivedMarkers: number;
    discoveredTestEntries: number;
    discoveredTestFiles: number;
    exemptCases: number;
    exemptMarkers: number;
    exemptTestEntries: number;
    mainMarkers: number;
    plannedAutomatedCases: number;
    reviewCases: number;
    reviewTriggers: number;
    unregisteredTestEntries: number;
  };
}
