/*
 * Generated test-evidence ledger CLI TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/test-evidence/api/test-evidence-ledger.d.mts
 * Source path: tools/test-evidence/api/test-evidence-ledger.d.mts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/test-evidence-review
 * Rebuild: bun run sync:test-evidence-cli
 */
import type { TestEntryInventory } from "./test-entry-inventory.types.mjs";
import type { TestEvidenceCaseShowResult } from "./test-evidence-case-show-result.types.mjs";
import type { TestEvidenceInspection } from "./test-evidence-inspection.types.mjs";
import type { TestEvidenceIndexSyncResult } from "./test-evidence-index-sync-result.types.mjs";
import type { TestEvidenceLedgerConfig } from "./test-evidence-ledger-config.types.mjs";
import type { TestEvidenceQueryResult } from "./test-evidence-query-result.types.mjs";
import type { TestEvidenceReport } from "./test-evidence-report.types.mjs";
import type { TestEvidenceStateIndex } from "./test-evidence-state-index.types.mjs";

export type StandardOutputSchema<T> = {
  readonly "~standard": {
    readonly types?: { readonly input: unknown; readonly output: T };
    readonly validate: (value: unknown) => unknown;
  };
};

export type ValidateTestEvidenceLedgerOptions = {
  config?: unknown;
  configPath?: string;
  inventory: unknown;
  inventorySource?: string;
  workspaceRoot: string;
};

export type ParsedTestEntryInventory = {
  diagnostics: TestEvidenceReport["diagnostics"];
  inventory: TestEntryInventory | null;
};

export type QueryTestEvidenceLedgerOptions = {
  config?: unknown;
  configPath?: string;
  limit?: number;
  offset?: number;
  query?: string;
  status?: "active" | "planned" | "all";
  triggered?: boolean;
  verification?: "automated" | "review" | "exempt" | "all";
  workspaceRoot: string;
};

export type ShowTestEvidenceCaseOptions = {
  caseId: string;
  config?: unknown;
  configPath?: string;
  workspaceRoot: string;
};

export type SyncTestEvidenceIndexOptions = {
  config?: unknown;
  configPath?: string;
  mode: "check" | "write";
  workspaceRoot: string;
};

export type TestEvidenceCaseView = TestEvidenceQueryResult["cases"][number];
export type TestEvidenceDiagnostic = TestEvidenceReport["diagnostics"][number];
export type TestEvidenceSummary = TestEvidenceReport["summary"];

export type {
  TestEntryInventory,
  TestEvidenceCaseShowResult,
  TestEvidenceInspection,
  TestEvidenceIndexSyncResult,
  TestEvidenceLedgerConfig,
  TestEvidenceQueryResult,
  TestEvidenceReport,
  TestEvidenceStateIndex
};

export declare const testEntryInventorySchema: StandardOutputSchema<TestEntryInventory>;
export declare const testEvidenceCaseShowResultSchema:
  StandardOutputSchema<TestEvidenceCaseShowResult>;
export declare const testEvidenceInspectionSchema: StandardOutputSchema<TestEvidenceInspection>;
export declare const testEvidenceIndexSyncResultSchema:
  StandardOutputSchema<TestEvidenceIndexSyncResult>;
export declare const testEvidenceLedgerConfigSchema: StandardOutputSchema<unknown>;
export declare const testEvidenceQueryResultSchema: StandardOutputSchema<TestEvidenceQueryResult>;
export declare const testEvidenceReportSchema: StandardOutputSchema<TestEvidenceReport>;
export declare const testEvidenceStateIndexSchema:
  StandardOutputSchema<TestEvidenceStateIndex>;

export declare function parseTestEntryInventory(
  value: unknown,
  source?: string
): ParsedTestEntryInventory;

export declare function inspectTestEvidenceLedger(
  options: ValidateTestEvidenceLedgerOptions
): Promise<TestEvidenceInspection>;

export declare function queryTestEvidenceLedger(
  options: QueryTestEvidenceLedgerOptions
): Promise<TestEvidenceQueryResult>;

export declare function showTestEvidenceCase(
  options: ShowTestEvidenceCaseOptions
): Promise<TestEvidenceCaseShowResult>;

export declare function syncTestEvidenceIndex(
  options: SyncTestEvidenceIndexOptions
): Promise<TestEvidenceIndexSyncResult>;

export declare function validateTestEvidenceLedger(
  options: ValidateTestEvidenceLedgerOptions
): Promise<TestEvidenceReport>;

export declare function runTestEvidenceLedgerCli(
  argv?: readonly string[]
): Promise<number>;
