await import("./archive.test.ts");
await import("./catalog.test.ts");
await import("./check.test.ts");
await import("./cli.test.ts");
await import("./generated-artifacts.test.ts");
await import("./git-distance.test.ts");
await import("./lifecycle.test.ts");
await import("./markdown.test.ts");
await import("./metadata.test.ts");
