/*
 * Generated change plan lifecycle CLI TypeScript declaration entry. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/change-plan/src/cli.ts
 * Source path: tools/change-plan/src/cli.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/change-plan
 * Rebuild: bun run sync:change-plan-cli
 */
export * from "./change-plan-sdk/cli.mjs";
