/*
 * Generated change plan lifecycle SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/change-plan/src/archive.ts
 * Source path: tools/change-plan/src/archive.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/change-plan
 * Rebuild: bun run sync:change-plan-cli
 */
import type { ChangePlanArchiveResult } from "./types.mjs";
export declare function archiveChangePlanDirectory(changeDirectoryInput: string): Promise<ChangePlanArchiveResult>;
