/*
 * Generated change plan lifecycle SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/change-plan/src/catalog.ts
 * Source path: tools/change-plan/src/catalog.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/change-plan
 * Rebuild: bun run sync:change-plan-cli
 */
import { type ChangePlanListOptions, type ChangePlanListResult, type ChangePlanShowResult, type ChangePlanStatus } from "./types.mjs";
export declare function changePlanStatusFromDirectory(changeDirectory: string): ChangePlanStatus;
export declare function listChangePlans(options?: ChangePlanListOptions): Promise<ChangePlanListResult>;
export declare function showChangePlanDirectory(changeDirectoryInput: string): Promise<ChangePlanShowResult>;
