/*
 * Generated ChangePlanMetadata schema-derived TypeScript declarations. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/change-plan/src/metadata.ts
 * Source path: tools/change-plan/src/metadata.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/change-plan
 * Rebuild: bun run sync:change-plan-cli
 */
export type ChangePlanMetadata =
  | {
      schemaVersion: 1;
      stage: "draft";
    }
  | {
      baseCommit: string | null;
      schemaVersion: 1;
      stage: "plan";
    }
  | {
      baseCommit: string;
      schemaVersion: 1;
      stage: "implementation";
    }
  | {
      baseCommit: string;
      schemaVersion: 1;
      shelf:
        | {
            atCommit: string;
            reason: string;
            source: "explicit";
          }
        | {
            atCommit: string;
            changedLines: number;
            commitCount: number;
            source: "git-distance-v1";
          };
      stage: "shelved";
    };
