/*
 * Generated change plan lifecycle SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/change-plan/src/check.ts
 * Source path: tools/change-plan/src/check.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/change-plan
 * Rebuild: bun run sync:change-plan-cli
 */
import { type ChangePlanArtifactCheckResult, type ChangePlanCheckResult, type ChangePlanStage } from "./types.mjs";
export declare function checkChangePlanArtifactsForStage(changeDirectoryInput: string, targetStage: ChangePlanStage): Promise<ChangePlanArtifactCheckResult>;
export declare function checkChangePlanDirectory(changeDirectoryInput: string): Promise<ChangePlanCheckResult>;
