/*
 * Generated change plan lifecycle SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/change-plan/src/cli.ts
 * Source path: tools/change-plan/src/cli.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/change-plan
 * Rebuild: bun run sync:change-plan-cli
 */
import { archiveChangePlanDirectory } from "./archive.mjs";
import { listChangePlans, showChangePlanDirectory } from "./catalog.mjs";
import { checkChangePlanDirectory } from "./check.mjs";
import { implementChangePlanDirectory, planChangePlanDirectory, reconcileChangePlanDirectory, resumeChangePlanDirectory, shelveChangePlanDirectory } from "./lifecycle.mjs";
import { ChangePlanMetadataError, parseChangePlanMetadata, readChangePlanMetadata } from "./metadata.mjs";
export declare function runChangePlanCli(argv?: readonly string[]): Promise<number>;
export { archiveChangePlanDirectory, checkChangePlanDirectory, implementChangePlanDirectory, listChangePlans, parseChangePlanMetadata, planChangePlanDirectory, readChangePlanMetadata, reconcileChangePlanDirectory, resumeChangePlanDirectory, shelveChangePlanDirectory, showChangePlanDirectory, ChangePlanMetadataError };
export type { ChangePlanAssessment, ChangePlanAssessmentName, ChangePlanArchiveResult, ChangePlanArtifactContents, ChangePlanArtifactName, ChangePlanArtifactCheckResult, ChangePlanCheckResult, ChangePlanDiagnostic, ChangePlanDiagnosticCode, ChangePlanFileName, ChangePlanLifecycleAction, ChangePlanLifecycleErrorCode, ChangePlanLifecycleFailure, ChangePlanLifecycleResult, ChangePlanLifecycleSuccess, ChangePlanListEntry, ChangePlanListOptions, ChangePlanListResult, ChangePlanListStatus, ChangePlanMetadata, ChangePlanMetadataName, ChangePlanShowResult, ChangePlanStage, ChangePlanStatus, ChangePlanTaskProgress, ChangePlanTaskSection, ChangePlanTaskSectionProgress } from "./types.mjs";
export type { ChangePlanMetadataErrorCode } from "./metadata.mjs";
