/*
 * Generated change plan lifecycle SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/change-plan/src/lifecycle.ts
 * Source path: tools/change-plan/src/lifecycle.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/change-plan
 * Rebuild: bun run sync:change-plan-cli
 */
import type { ChangePlanLifecycleResult } from "./types.mjs";
export declare function planChangePlanDirectory(changeDirectoryInput: string): Promise<ChangePlanLifecycleResult<"plan">>;
export declare function implementChangePlanDirectory(changeDirectoryInput: string): Promise<ChangePlanLifecycleResult<"implement">>;
export declare function shelveChangePlanDirectory(changeDirectoryInput: string, reasonInput: string): Promise<ChangePlanLifecycleResult<"shelve">>;
export declare function reconcileChangePlanDirectory(changeDirectoryInput: string): Promise<ChangePlanLifecycleResult<"reconcile">>;
export declare function resumeChangePlanDirectory(changeDirectoryInput: string): Promise<ChangePlanLifecycleResult<"resume">>;
