/*
 * Generated change plan lifecycle SDK TypeScript declaration. Do not edit this file directly.
 * Repository: https://github.com/zxyycom/skills
 * Maintained source: https://github.com/zxyycom/skills/blob/main/tools/change-plan/src/metadata.ts
 * Source path: tools/change-plan/src/metadata.ts
 * Skill source directory: https://github.com/zxyycom/skills/tree/main/skills/change-plan
 * Rebuild: bun run sync:change-plan-cli
 */
import type { ChangePlanMetadata } from "./change-plan-metadata.types.mjs";
export type { ChangePlanMetadata } from "./change-plan-metadata.types.mjs";
export type ChangePlanMetadataErrorCode = "metadata-invalid-json" | "metadata-invalid-schema" | "metadata-not-found" | "metadata-not-regular-file" | "metadata-read-failed" | "metadata-symbolic-link" | "metadata-write-failed";
export declare class ChangePlanMetadataError extends Error {
    readonly code: ChangePlanMetadataErrorCode;
    constructor(code: ChangePlanMetadataErrorCode, message: string);
}
export declare function parseChangePlanMetadata(value: unknown): ChangePlanMetadata;
export declare function readChangePlanMetadata(changeDirectory: string): Promise<ChangePlanMetadata>;
